language: node_js
node_js:
- '7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache: yarn
script:
- npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    repo: LukeSheard/lukesheard.github.io
    branch: dev