language: node_js
node_js:
- '7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache: yarn
before_script:
- 
script:
- npm run build

deploy:
  provider: script
  script: deploy
  on:
    branch: dev