name: "Luke Sheard"
description: ""

url: "http://www.lukesheard.com/"

collections:
- posts
- jobs

paginate: 12
paginate_path: "/blog/page:num/"

markdown: rdiscount
permalink: /blog/:year/:title
highlighter: pygments

navigation:
- text: Home
  url: /
  ref: /index.html
- text: About
  url: /about/
  ref: /about/index.html
- text: Blog
  url: /blog/
  ref: /blog/index.html