name: "Luke Sheard"
description: ""

url: "http://lukesheard.github.io/"

collections:
- posts
- jobs

paginate: 8

markdown: rdiscount
permalink: /blog/:year/:title
highlighter: pygments

navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Blog
  url: /blog/