name: "Luke Sheard"
description: ""

url: "http://www.lukesheard.com"

collections:
 jobs:
 portfolio:
   output: true
   permalink: "/portfolio/:title/"


paginate: 12
paginate_path: "/blog/page:num/"

markdown: rdiscount
permalink: /blog/:year/:title
highlighter: pygments

navigation:
- text: Home
  type: link
  url: /
- text: About
  type: dropdown
  pages: [Resume]
  url: /about/
- text: Blog
  type: dropdown
  pages: [America]
  url: /blog/
# - text: Portfolio
#   type: link
#   url: /portfolio/