name: "Luke Sheard"
description: ""

url: "http://www.lukesheard.com"

collections:
 jobs:
 shows:
   output: true
   permalink: "/shows/:title/"


paginate: 12
paginate_path: "/blog/page:num/"

markdown: rdiscount
permalink: /blog/:year/:title
highlighter: pygments

navigation:
- text: Home
  url: /
  ref: /index.html
- text: About
  url: /about/
  ref: /about/index.html
- text: Blog
  url: /blog/
  ref: /blog/index.html
- text: Shows
  url: /shows/
  ref: /shows/index.html